# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Language-Hungarian
version:      0.01
version_from: Hungarian.pm
installdirs:  site
requires:
    Time::Date:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
